In [3]:
import tensorflow as tf
#from tensorflow import keras
import numpy as np
import pandas as pd

In [4]:
import keras

In [6]:
con_df = pd.read_csv("C:/Users/User/Downloads/concrete_data.csv")
con_df

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [14]:
con_df.shape

(1030, 9)

In [23]:
predictors = con_df.drop(columns="Strength")
target = con_df["Strength"]

In [34]:
norm_predicts = (predictors - predictors.mean())/predictors.std()
norm_predicts

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
...,...,...,...,...,...,...,...,...
1025,-0.045623,0.487998,0.564271,-0.092126,0.451190,-1.322363,-0.065861,-0.279597
1026,0.392628,-0.856472,0.959602,0.675872,0.702285,-1.993711,0.496651,-0.279597
1027,-1.269472,0.759210,0.850222,0.521336,-0.017520,-1.035561,0.080068,-0.279597
1028,-1.168042,1.307430,-0.846733,-0.279443,0.852942,0.214537,0.191074,-0.279597
1029,-0.193939,0.308349,0.376762,0.891286,0.400971,-1.394385,-0.150675,-0.279597

In [35]:
in_num = norm_predicts.shape[1]

In [36]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [65]:
def regression_model():
    model = Sequential()
    model.add(Input(shape=(in_num,)))
    model.add(Dense(256, activation='relu'))
    model.add(Dense(80, activation='relu'))
    model.add(Dense(42, activation='relu'))
    model.add(Dense(1))

    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [66]:
concrete_model = regression_model()

In [73]:
concrete_model.fit(norm_predicts, target, validation_split=0.3, verbose=2, epochs=100)

Epoch 1/100
23/23 - 0s - 5ms/step - loss: 769.1297 - val_loss: 216.6988
Epoch 2/100
23/23 - 0s - 4ms/step - loss: 267.5758 - val_loss: 192.9583
Epoch 3/100
23/23 - 0s - 4ms/step - loss: 214.1109 - val_loss: 178.8638
Epoch 4/100
23/23 - 0s - 4ms/step - loss: 194.5758 - val_loss: 177.5477
Epoch 5/100
23/23 - 0s - 4ms/step - loss: 178.8541 - val_loss: 174.7772
Epoch 6/100
23/23 - 0s - 4ms/step - loss: 170.1202 - val_loss: 167.4423
Epoch 7/100
23/23 - 0s - 4ms/step - loss: 161.7194 - val_loss: 170.2441
Epoch 8/100
23/23 - 0s - 4ms/step - loss: 152.7125 - val_loss: 173.6744
Epoch 9/100
23/23 - 0s - 4ms/step - loss: 146.1668 - val_loss: 172.5884
Epoch 10/100
23/23 - 0s - 4ms/step - loss: 138.3191 - val_loss: 167.0708
Epoch 11/100
23/23 - 0s - 4ms/step - loss: 132.2100 - val_loss: 184.5913
Epoch 12/100
23/23 - 0s - 4ms/step - loss: 125.5154 - val_loss: 166.7573
Epoch 13/100
23/23 - 0s - 4ms/step - loss: 119.0943 - val_loss: 181.6183
Epoch 14/100
23/23 - 0s - 4ms/step - loss: 111.9534 - val_loss: 168.9819
Epoch 15/100
23/23 - 0s - 4ms/step - loss: 106.2568 - val_loss: 179.1504
Epoch 16/100
23/23 - 0s - 4ms/step - loss: 100.7312 - val_loss: 166.7438
Epoch 17/100
23/23 - 0s - 4ms/step - loss: 98.0791 - val_loss: 188.1008
Epoch 18/100
23/23 - 0s - 4ms/step - loss: 88.7652 - val_loss: 178.1323
Epoch 19/100
23/23 - 0s - 4ms/step - loss: 82.8218 - val_loss: 193.2164
Epoch 20/100
23/23 - 0s - 4ms/step - loss: 78.8061 - val_loss: 171.3401
Epoch 21/100
23/23 - 0s - 4ms/step - loss: 75.7808 - val_loss: 159.8254
Epoch 22/100
23/23 - 0s - 4ms/step - loss: 72.7204 - val_loss: 178.5048
Epoch 23/100
23/23 - 0s - 4ms/step - loss: 66.9787 - val_loss: 167.4385
Epoch 24/100
23/23 - 0s - 4ms/step - loss: 61.0364 - val_loss: 187.9068
Epoch 25/100
23/23 - 0s - 4ms/step - loss: 58.6968 - val_loss: 179.6566
Epoch 26/100
23/23 - 0s - 4ms/step - loss: 55.2247 - val_loss: 179.4799
Epoch 27/100
23/23 - 0s - 4ms/step - loss: 52.5511 - val_loss: 184.6319
Epoch 28/100
23/23 - 0s - 4ms/step - loss: 53.8451 - val_loss: 201.4704
Epoch 29/100
23/23 - 0s - 4ms/step - loss: 49.4716 - val_loss: 183.3685
Epoch 30/100
23/23 - 0s - 4ms/step - loss: 46.9348 - val_loss: 169.7802
Epoch 31/100
23/23 - 0s - 4ms/step - loss: 46.5269 - val_loss: 184.9887
Epoch 32/100
23/23 - 0s - 4ms/step - loss: 44.6492 - val_loss: 200.1997
Epoch 33/100
23/23 - 0s - 4ms/step - loss: 43.4100 - val_loss: 174.3911
Epoch 34/100
23/23 - 0s - 4ms/step - loss: 40.1590 - val_loss: 182.8723
Epoch 35/100
23/23 - 0s - 4ms/step - loss: 38.6144 - val_loss: 181.1725
Epoch 36/100
23/23 - 0s - 4ms/step - loss: 39.0911 - val_loss: 206.3110
Epoch 37/100
23/23 - 0s - 4ms/step - loss: 37.9184 - val_loss: 170.2657
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 36.5364 - val_loss: 167.6099
Epoch 39/100
23/23 - 0s - 4ms/step - loss: 36.1537 - val_loss: 198.7698
Epoch 40/100
23/23 - 0s - 4ms/step - loss: 35.4907 - val_loss: 162.1049
Epoch 41/100
23/23 - 0s - 4ms/step - loss: 33.9814 - val_loss: 156.0181
Epoch 42/100
23/23 - 0s - 4ms/step - loss: 32.2665 - val_loss: 169.4080
Epoch 43/100
23/23 - 0s - 4ms/step - loss: 30.6801 - val_loss: 163.6545
Epoch 44/100
23/23 - 0s - 4ms/step - loss: 29.9459 - val_loss: 184.3780
Epoch 45/100
23/23 - 0s - 4ms/step - loss: 29.9181 - val_loss: 126.7987
Epoch 46/100
23/23 - 0s - 4ms/step - loss: 31.9920 - val_loss: 127.6516
Epoch 47/100
23/23 - 0s - 4ms/step - loss: 29.9391 - val_loss: 168.7677
Epoch 48/100
23/23 - 0s - 4ms/step - loss: 28.1516 - val_loss: 153.9693
Epoch 49/100
23/23 - 0s - 4ms/step - loss: 27.3604 - val_loss: 157.3990
Epoch 50/100
23/23 - 0s - 4ms/step - loss: 26.9991 - val_loss: 133.9599
Epoch 51/100
23/23 - 0s - 4ms/step - loss: 25.8950 - val_loss: 152.8875
Epoch 52/100
23/23 - 0s - 4ms/step - loss: 24.7474 - val_loss: 151.8385
Epoch 53/100
23/23 - 0s - 4ms/step - loss: 25.3246 - val_loss: 136.4619
Epoch 54/100
23/23 - 0s - 4ms/step - loss: 24.1911 - val_loss: 151.7757
Epoch 55/100
23/23 - 0s - 4ms/step - loss: 23.6879 - val_loss: 160.2722
Epoch 56/100
23/23 - 0s - 4ms/step - loss: 24.2747 - val_loss: 145.5045
Epoch 57/100
23/23 - 0s - 4ms/step - loss: 23.3239 - val_loss: 144.2556
Epoch 58/100
23/23 - 0s - 4ms/step - loss: 24.2505 - val_loss: 139.6404
Epoch 59/100
23/23 - 0s - 4ms/step - loss: 21.5791 - val_loss: 166.7266
Epoch 60/100
23/23 - 0s - 4ms/step - loss: 21.9002 - val_loss: 157.6680
Epoch 61/100
23/23 - 0s - 4ms/step - loss: 22.2173 - val_loss: 160.3902
Epoch 62/100
23/23 - 0s - 4ms/step - loss: 21.3752 - val_loss: 131.3923
Epoch 63/100
23/23 - 0s - 4ms/step - loss: 20.8498 - val_loss: 159.2365
Epoch 64/100
23/23 - 0s - 4ms/step - loss: 21.1498 - val_loss: 150.8566
Epoch 65/100
23/23 - 0s - 4ms/step - loss: 20.5083 - val_loss: 162.8798
Epoch 66/100
23/23 - 0s - 4ms/step - loss: 20.6705 - val_loss: 126.6767
Epoch 67/100
23/23 - 0s - 4ms/step - loss: 19.1054 - val_loss: 156.5145
Epoch 68/100
23/23 - 0s - 4ms/step - loss: 19.9911 - val_loss: 143.7839
Epoch 69/100
23/23 - 0s - 4ms/step - loss: 19.7314 - val_loss: 148.2323
Epoch 70/100
23/23 - 0s - 4ms/step - loss: 19.1207 - val_loss: 134.5486
Epoch 71/100
23/23 - 0s - 4ms/step - loss: 20.6003 - val_loss: 121.5089
Epoch 72/100
23/23 - 0s - 4ms/step - loss: 18.3024 - val_loss: 146.6857
Epoch 73/100
23/23 - 0s - 4ms/step - loss: 17.8715 - val_loss: 142.1576
Epoch 74/100
23/23 - 0s - 4ms/step - loss: 17.7232 - val_loss: 136.4025
Epoch 75/100
23/23 - 0s - 4ms/step - loss: 17.6020 - val_loss: 149.1839
Epoch 76/100
23/23 - 0s - 4ms/step - loss: 17.9616 - val_loss: 133.0507
Epoch 77/100
23/23 - 0s - 4ms/step - loss: 17.3378 - val_loss: 173.1088
Epoch 78/100
23/23 - 0s - 4ms/step - loss: 17.6722 - val_loss: 136.2331
Epoch 79/100
23/23 - 0s - 4ms/step - loss: 16.8634 - val_loss: 154.9980
Epoch 80/100
23/23 - 0s - 4ms/step - loss: 16.7170 - val_loss: 135.8779
Epoch 81/100
23/23 - 0s - 4ms/step - loss: 16.2040 - val_loss: 109.6274
Epoch 82/100
23/23 - 0s - 4ms/step - loss: 16.4833 - val_loss: 147.9354
Epoch 83/100
23/23 - 0s - 4ms/step - loss: 16.9218 - val_loss: 187.0385
Epoch 84/100
23/23 - 0s - 4ms/step - loss: 18.1394 - val_loss: 117.6175
Epoch 85/100
23/23 - 0s - 4ms/step - loss: 16.6367 - val_loss: 141.9292
Epoch 86/100
23/23 - 0s - 4ms/step - loss: 15.9163 - val_loss: 130.7631
Epoch 87/100
23/23 - 0s - 4ms/step - loss: 16.1557 - val_loss: 147.6647
Epoch 88/100
23/23 - 0s - 4ms/step - loss: 15.8818 - val_loss: 161.3497
Epoch 89/100
23/23 - 0s - 4ms/step - loss: 15.9331 - val_loss: 156.0143
Epoch 90/100
23/23 - 0s - 4ms/step - loss: 15.5577 - val_loss: 152.2251
Epoch 91/100
23/23 - 0s - 4ms/step - loss: 15.6072 - val_loss: 132.8428
Epoch 92/100
23/23 - 0s - 4ms/step - loss: 15.2796 - val_loss: 162.7534
Epoch 93/100
23/23 - 0s - 4ms/step - loss: 14.9819 - val_loss: 112.3212
Epoch 94/100
23/23 - 0s - 4ms/step - loss: 15.5630 - val_loss: 146.6115
Epoch 95/100
23/23 - 0s - 4ms/step - loss: 15.4397 - val_loss: 125.6376
Epoch 96/100
23/23 - 0s - 4ms/step - loss: 14.9420 - val_loss: 152.5181
Epoch 97/100
23/23 - 0s - 4ms/step - loss: 15.9938 - val_loss: 150.0421
Epoch 98/100
23/23 - 0s - 4ms/step - loss: 14.5248 - val_loss: 141.4607
Epoch 99/100
23/23 - 0s - 4ms/step - loss: 15.7737 - val_loss: 135.1643
Epoch 100/100
23/23 - 0s - 4ms/step - loss: 16.1980 - val_loss: 147.7835

In [74]:
def regression_model_upt():
    model = Sequential()
    model.add(Input(shape=(in_num,)))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(25, activation='relu'))
    model.add(Dense(36, activation='relu'))
    model.add(Dense(25, activation='relu'))
    model.add(Dense(1))

    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [75]:
model = regression_model_upt()

In [77]:
model.fit(norm_predicts, target, validation_split=0.10, verbose=1, validation_batch_size=50, epochs=100)

Epoch 1/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.8962 - val_loss: 18.0443
Epoch 2/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.1383 - val_loss: 16.9846
Epoch 3/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.3970 - val_loss: 14.2310
Epoch 4/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1572 - val_loss: 13.7993
Epoch 5/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0094 - val_loss: 15.3045
Epoch 6/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9676 - val_loss: 16.2800
Epoch 7/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.8447 - val_loss: 14.3850
Epoch 8/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2265 - val_loss: 20.9655
Epoch 9/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9442 - val_loss: 18.1752
Epoch 10/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.7723 - val_loss: 15.0703
Epoch 11/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.4364 - val_loss: 15.7996
Epoch 12/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.4531 - val_loss: 16.2001
Epoch 13/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.8318 - val_loss: 16.6138
Epoch 14/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9225 - val_loss: 15.0712
Epoch 15/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.9163 - val_loss: 14.5044
Epoch 16/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.8478 - val_loss: 18.6061
Epoch 17/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.5247 - val_loss: 22.9283
Epoch 18/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.2969 - val_loss: 13.9516
Epoch 19/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4165 - val_loss: 13.3333
Epoch 20/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.9416 - val_loss: 18.3290
Epoch 21/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9060 - val_loss: 13.9536
Epoch 22/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6477 - val_loss: 15.8485
Epoch 23/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.8577 - val_loss: 13.0308
Epoch 24/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5434 - val_loss: 15.3122
Epoch 25/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.4764 - val_loss: 14.5358
Epoch 26/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3686 - val_loss: 14.1617
Epoch 27/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.7639 - val_loss: 13.5901
Epoch 28/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0876 - val_loss: 14.4422
Epoch 29/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.3194 - val_loss: 12.8086
Epoch 30/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.7880 - val_loss: 13.3038
Epoch 31/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.7200 - val_loss: 14.1488
Epoch 32/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3188 - val_loss: 12.9430
Epoch 33/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2618 - val_loss: 14.7815
Epoch 34/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2185 - val_loss: 14.2628
Epoch 35/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.2538 - val_loss: 13.3117
Epoch 36/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3604 - val_loss: 14.1686
Epoch 37/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.6639 - val_loss: 16.2093
Epoch 38/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8752 - val_loss: 12.2122
Epoch 39/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.0793 - val_loss: 13.2012
Epoch 40/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8820 - val_loss: 13.6033
Epoch 41/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3727 - val_loss: 13.5394
Epoch 42/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0706 - val_loss: 12.4446
Epoch 43/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8845 - val_loss: 13.0390
Epoch 44/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9948 - val_loss: 15.6146
Epoch 45/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0821 - val_loss: 30.2099
Epoch 46/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2353 - val_loss: 13.4338
Epoch 47/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9380 - val_loss: 14.4917
Epoch 48/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.2974 - val_loss: 12.6839
Epoch 49/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.0926 - val_loss: 11.2577
Epoch 50/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9672 - val_loss: 12.0309
Epoch 51/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3160 - val_loss: 12.1322
Epoch 52/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9230 - val_loss: 12.3542
Epoch 53/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8518 - val_loss: 11.4023
Epoch 54/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9971 - val_loss: 12.6122
Epoch 55/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.8176 - val_loss: 13.3468
Epoch 56/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.1102 - val_loss: 12.3973
Epoch 57/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6107 - val_loss: 14.0735
Epoch 58/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0285 - val_loss: 10.3741
Epoch 59/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.3068 - val_loss: 11.4151
Epoch 60/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.9903 - val_loss: 11.1647
Epoch 61/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9458 - val_loss: 13.0390
Epoch 62/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.4076 - val_loss: 13.6592
Epoch 63/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.2672 - val_loss: 12.8241
Epoch 64/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.7746 - val_loss: 12.9258
Epoch 65/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.9325 - val_loss: 15.6992
Epoch 66/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.0751 - val_loss: 22.6877
Epoch 67/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8787 - val_loss: 10.7023
Epoch 68/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.8168 - val_loss: 12.5585
Epoch 69/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2289 - val_loss: 27.1531
Epoch 70/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6310 - val_loss: 13.0945
Epoch 71/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.4104 - val_loss: 11.3172
Epoch 72/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.4396 - val_loss: 10.8110
Epoch 73/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.1093 - val_loss: 15.8081
Epoch 74/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.7780 - val_loss: 11.9761
Epoch 75/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.4409 - val_loss: 10.8230
Epoch 76/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.9231 - val_loss: 10.7286
Epoch 77/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.3724 - val_loss: 12.5118
Epoch 78/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.7985 - val_loss: 17.6378
Epoch 79/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6983 - val_loss: 11.3846
Epoch 80/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.7869 - val_loss: 13.2434
Epoch 81/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9879 - val_loss: 12.1517
Epoch 82/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.1764 - val_loss: 9.9464
Epoch 83/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.3026 - val_loss: 12.7243
Epoch 84/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.2040 - val_loss: 11.6822
Epoch 85/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.8348 - val_loss: 10.3913
Epoch 86/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4089 - val_loss: 11.0689
Epoch 87/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.1746 - val_loss: 12.4097
Epoch 88/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9117 - val_loss: 10.7626
Epoch 89/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.0323 - val_loss: 12.1259
Epoch 90/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.1317 - val_loss: 11.5652
Epoch 91/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.2187 - val_loss: 11.5170
Epoch 92/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4014 - val_loss: 12.9757
Epoch 93/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3237 - val_loss: 12.4951
Epoch 94/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.2601 - val_loss: 10.5381
Epoch 95/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4734 - val_loss: 10.6397
Epoch 96/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.5465 - val_loss: 9.8693
Epoch 97/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.6385 - val_loss: 13.1139
Epoch 98/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.6354 - val_loss: 12.7677
Epoch 99/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.0121 - val_loss: 12.1536
Epoch 100/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.2792 - val_loss: 10.2625

In [93]:
sample = norm_predicts.sample(1)
sample_in = sample.index[0]
pred_y = model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

In [94]:
target[sample_in] - pred_y

array([[1.74378326]])