In [1]:
import pandas as pd

csvfile = pd.read_csv("weather.csv")

csvfile.head()

   Season  Humidity  Wind Speed  Temperature  Moisture Content
0  Summer        42           4           27                23
1  Summer        57           3           23                27
2  Summer        36           4           34                19
3    Fall        32          15           30                15
4    Fall        45          12           25                17

In [2]:
csvfile.to_csv("output.csv", index=False)

In [3]:
csvfile.describe()

        Humidity  Wind Speed  Temperature  Moisture Content
count  12.000000   12.000000     12.00000         12.000000
mean   38.250000    8.333333     24.50000         19.416667
std     7.782556    4.163332      5.97723          4.077841
min    29.000000    3.000000     13.00000         12.000000
25%    32.750000    4.000000     21.75000         16.750000
50%    36.500000    8.000000     25.00000         19.500000
75%    42.250000   12.000000     28.25000         22.250000
max    57.000000   15.000000     34.00000         27.000000

In [4]:
import numpy as np
hum_data = csvfile["Humidity"].values.astype("float32")
type(hum_data)

numpy.ndarray

In [5]:
sorted_hd = np.sort(hum_data)

In [6]:
p=50
position = round(p*(len(sorted_hd)+1)/100)

In [7]:
sorted_hd[position]

np.float32(37.0)

In [8]:
sorted_hd

array([29., 31., 32., 33., 34., 36., 37., 40., 42., 43., 45., 57.],
      dtype=float32)

In [9]:
import openpyxl
xlfile = pd.read_excel("excel.xlsx", index_col=False, engine="openpyxl")
xlfile.head()

       Name  Age Department  Salary
0    Andrew   34         IT   50000
1    Aubrey   39  Marketing   85000
2  Kendrick   35         IT   65000
3      Tony   27         HR   45000
4      Yeat   24    Finance   60000

In [10]:
xlfile.to_excel("output.xlsx", index=False, engine="openpyxl")

In [11]:
all_sheet = pd.read_excel("C:/Users/User/OneDrive/Documents/DJI DRONE PRICE DATASHEET.xlsx", sheet_name=None, engine="openpyxl")
print(all_sheet.keys())

dict_keys(['GENERAL', 'MINI 2|4K SERIES', 'MAVIC AIR 2 SERIES', 'CODE NAME'])

In [12]:
with pd.ExcelWriter("multi_output.xlsx", engine="openpyxl") as writer:
    csvfile.to_excel(writer, sheet_name="Weather_Data", index=False)
    xlfile.to_excel(writer, sheet_name="Excel_Data", index=False)

In [13]:
multi_sheet = pd.read_excel("multi_output.xlsx", sheet_name=None, engine="openpyxl")
print(multi_sheet.keys())

dict_keys(['Weather_Data', 'Excel_Data'])

In [14]:
xlfile["Performance Points"] = [2, 3, 3, 4, 1, 2]
xlfile["Bonus"] = round(xlfile["Salary"] * (.005+(xlfile["Age"])/360)) * xlfile["Performance Points"]/5

In [15]:
xlfile.head(10)

       Name  Age      Department  Salary  Performance Points   Bonus
0    Andrew   34              IT   50000                   2  1988.8
1    Aubrey   39       Marketing   85000                   3  5779.8
2  Kendrick   35              IT   65000                   3  3986.4
3      Tony   27              HR   45000                   4  2880.0
4      Yeat   24         Finance   60000                   1   860.0
5      Carl   47  Administrative  145000                   2  7862.4

In [20]:
sorted_xlfile = xlfile.sort_values(by="Salary", ascending=True)
print(sorted_xlfile)

filter_IT = xlfile[xlfile["Department"] == "IT"]
print(filter_IT)

       Name  Age      Department  Salary  Performance Points   Bonus
3      Tony   27              HR   45000                   4  2880.0
0    Andrew   34              IT   52500                   2  1988.8
4      Yeat   24         Finance   60000                   1   860.0
2  Kendrick   35              IT   68250                   3  3986.4
1    Aubrey   39       Marketing   85000                   3  5779.8
5      Carl   47  Administrative  145000                   2  7862.4
       Name  Age Department  Salary  Performance Points   Bonus
0    Andrew   34         IT   52500                   2  1988.8
2  Kendrick   35         IT   68250                   3  3986.4

In [19]:
xlfile.loc[xlfile["Department"] == "IT", "Salary"] *= 1.05
xlfile["Salary"] = np.around(xlfile["Salary"], decimals=2)